steps:
- task: Prisma Cloud IaC Scan@2
  name: CFT_variable_files
  continueOnError: true
  inputs:
    Path: './CFT_variable_files'
    prismaCloudService: 'QA'
    High: '100'
    Medium: '100'
    Low: '100'
    Operator: 'or'
    Tags: 'step:scan'
- task: Prisma Cloud IaC Scan@2
  name: CFT_variable_values
  continueOnError: true
  inputs:
    Path: './CFT_variable_values'
    prismaCloudService: 'QA'
    High: '100'
    Medium: '100'
    Low: '100'
    Operator: 'or'
    Tags: 'step:scan'
- task: Prisma Cloud IaC Scan@2
  name: tf12_variable_files
  continueOnError: true
  inputs:
    Path: './TF/tf12_variable_files'
    prismaCloudService: 'QA'
    High: '100'
    Medium: '100'
    Low: '100'
    Operator: 'or'
    Tags: 'step:scan'
- task: Prisma Cloud IaC Scan@2
  name: tf12_variable_values
  continueOnError: true
  inputs:
    Path: './TF/tf12_variable_values'
    prismaCloudService: 'QA'
    High: '100'
    Medium: '100'
    Low: '100'
    Operator: 'or'
    Tags: 'step:scan'        