steps:
- task: Prisma Cloud IaC Scan@2
  name: scan
  continueOnError: true
  inputs:
    Path: './CFT_variable_files'
    prismaCloudService: 'Stage'
    High: '100'
    Medium: '100'
    Low: '100'
    Operator: 'or'
    Tags: 'step:scan'
- task: Prisma Cloud IaC Scan@2
  name: scan
  continueOnError: true
  inputs:
    Path: './CFT_variable_values'
    prismaCloudService: 'Stage'
    High: '100'
    Medium: '100'
    Low: '100'
    Operator: 'or'
    Tags: 'step:scan'
- task: Prisma Cloud IaC Scan@2
  name: scan
  continueOnError: true
  inputs:
    Path: './TF/tf12_variable_files'
    prismaCloudService: 'Stage'
    High: '100'
    Medium: '100'
    Low: '100'
    Operator: 'or'
    Tags: 'step:scan'
- task: Prisma Cloud IaC Scan@2
  name: scan
  continueOnError: true
  inputs:
    Path: './TF/tf12_variable_values'
    prismaCloudService: 'Stage'
    High: '100'
    Medium: '100'
    Low: '100'
    Operator: 'or'
    Tags: 'step:scan'        