steps:
- task: Prisma Cloud IaC Scan@2
  name: scan
  continueOnError: true
  inputs:
    Path: '.'
    prismaCloudService: 'Stage'
    High: '100'
    Medium: '100'
    Low: '100'
    Operator: 'or'
    Tags: 'step:scan'
